### ISSUE TITLE
Keyboard forces capital letters

### ISSUE THREAD

**Issue by AaronPerl** [aeksco/lyrebird#10]
Because the text field empties itself, some keyboards will automatically return to caps lock being on, meaning that capital letters are typed. Currently capital letters do not work, so this results in no letters being typed.

**Comment by aeksco** [comment]
HA - awesome. I'll Update the codebase this morning not to flush the text field and look into pushing an .apk build of the app with the commit.

**Comment by aeksco** [comment]
Updated code base - capital letters are still and issue.

**Comment by aeksco** [comment]
Resolved in latest build
